services:
  # Web Service
  - type: web
    name: shifa-alhind
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: shifa-alhind-db
          property: connectionString
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_S3_BUCKET
        sync: false
      - key: EMAIL_SERVER_HOST
        sync: false
      - key: EMAIL_SERVER_PORT
        value: 587
      - key: EMAIL_SERVER_USER
        sync: false
      - key: EMAIL_SERVER_PASSWORD
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: NEXT_PUBLIC_GA_ID
        sync: false
      - key: SENTRY_DSN
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: shifa-alhind-db
    plan: starter
    databaseName: shifaalhind
    user: shifaalhind
    region: oregon
